environment_path = "/Users/philipbeadle/holochain-2020/conductor-admin/server/conductor/files"

[passphrase_service]
type = "cmd"

[[admin_interfaces]]
[admin_interfaces.driver]
type = "websocket"
port = 7778
